# Auto-generated by scripts/generate_models.py — do not edit manually.
# Run `make generate-models` to regenerate from SQL migrations.

import enum

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass

class RegistryType(enum.Enum):
    pypi = 'pypi'
    npm = 'npm'

class SeverityType(enum.Enum):
    CRITICAL = 'CRITICAL'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'

class Example(Base):
    __tablename__ = "example"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), nullable=False)
    description = Column(Text)
    is_active = Column(Boolean, nullable=False, server_default=text('TRUE'))
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

class Package(Base):
    __tablename__ = "package"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    registry = Column(Enum(RegistryType, name='registry_type'), nullable=False)
    name = Column(Text, nullable=False)
    normalized_name = Column(Text, nullable=False)
    summary = Column(Text)
    description = Column(Text)
    homepage_url = Column(Text)
    repository_url = Column(Text)
    documentation_url = Column(Text)
    license = Column(Text)
    keywords = Column(ARRAY(Text))
    classifiers = Column(ARRAY(Text))
    requires_python = Column(Text)
    author = Column(Text)
    author_email = Column(Text)
    maintainers = Column(JSON)
    first_release_at = Column(DateTime(timezone=True))
    latest_release_at = Column(DateTime(timezone=True))
    is_deprecated = Column(Boolean, nullable=False, server_default=text('FALSE'))
    is_yanked = Column(Boolean, nullable=False, server_default=text('FALSE'))
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    crawled_at = Column(DateTime(timezone=True))
    search_vector = Column(Text)

    package_versions = relationship("PackageVersion", back_populates="package")
    download_stats = relationship("DownloadStat", back_populates="package")
    vulnerabilities = relationship("Vulnerability", back_populates="package")
    reputation_scores = relationship("ReputationScore", back_populates="package")

class PackageVersion(Base):
    __tablename__ = "package_version"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    package_id = Column(BigInteger, ForeignKey('package.id'), nullable=False)
    version = Column(Text, nullable=False)
    release_date = Column(DateTime(timezone=True))
    dependencies = Column(JSON)
    dep_count = Column(Integer, nullable=False, server_default=text('0'))
    size_bytes = Column(BigInteger)
    is_yanked = Column(Boolean, nullable=False, server_default=text('FALSE'))
    is_latest = Column(Boolean, nullable=False, server_default=text('FALSE'))

    package = relationship("Package", back_populates="package_versions")

class DownloadStat(Base):
    __tablename__ = "download_stat"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    package_id = Column(BigInteger, ForeignKey('package.id'), nullable=False)
    period = Column(Text, nullable=False)
    date = Column(Date, nullable=False)
    download_count = Column(BigInteger, nullable=False, server_default=text('0'))

    package = relationship("Package", back_populates="download_stats")

class Vulnerability(Base):
    __tablename__ = "vulnerability"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    package_id = Column(BigInteger, ForeignKey('package.id'), nullable=False)
    cve_id = Column(Text)
    advisory_id = Column(Text)
    severity = Column(Enum(SeverityType, name='severity_type'))
    summary = Column(Text)
    affected_versions = Column(Text)
    fixed_version = Column(Text)
    published_at = Column(DateTime(timezone=True))
    source = Column(Text)
    source_url = Column(Text)

    package = relationship("Package", back_populates="vulnerabilities")

class ReputationScore(Base):
    __tablename__ = "reputation_score"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    package_id = Column(BigInteger, ForeignKey('package.id'), nullable=False, unique=True)
    maintenance = Column(Float, nullable=False, server_default=text('0.0'))
    vulnerability = Column(Float, nullable=False, server_default=text('0.0'))
    dependency = Column(Float, nullable=False, server_default=text('0.0'))
    popularity = Column(Float, nullable=False, server_default=text('0.0'))
    maintainer = Column(Float, nullable=False, server_default=text('0.0'))
    license = Column(Float, nullable=False, server_default=text('0.0'))
    overall_score = Column(Float, nullable=False, server_default=text('0.0'))
    score_details = Column(JSON)
    computed_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    package = relationship("Package", back_populates="reputation_scores")

class CrawlState(Base):
    __tablename__ = "crawl_state"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    registry = Column(Enum(RegistryType, name='registry_type'), nullable=False)
    task_type = Column(Text, nullable=False)
    cursor = Column(Text)
    status = Column(Text, nullable=False, server_default=text('idle'))
    last_run_at = Column(DateTime(timezone=True))
    error_message = Column(Text)
